### ISSUE TITLE
print product label

### ISSUE THREAD

**Issue by Patrickkappert** [beescoop/Obeesdoo#217]
There is an externel ID error when I want to print a product label with the special label information.

**Comment by robinkeunen** [comment]
Hi @Patrickkappert 

Can you provide the stack trace and/or a PR fix?

**Comment by Patrickkappert** [comment]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/odoo/odoo-server/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.view', <function View.get_view_id at 0x7f9848953430>, 2, 'product_label_report.report_producttemplatelabel', (None,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/odoo/odoo-server/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f984b0115e0>, 'product_label_report.report_producttemplatelabel')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1679, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter)
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/custom/addons/server-tools/excel_import_export/controllers/main.py", line 52, in report_routes
    return super(ReportController, self).report_routes(
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/custom/addons/reporting-engine/report_xlsx_helper/controllers/main.py", line 53, in report_routes
    return super(ReportController, self).report_routes(
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/custom/addons/reporting-engine/report_xlsx/controllers/main.py", line 58, in report_routes
    return super(ReportController, self).report_routes(
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1620, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/odoo/custom/addons/mis-builder/mis_builder/report/mis_report_instance_qweb.py", line 28, in render_qweb_pdf
    return super(Report, self).render_qweb_pdf(res_ids, data)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 727, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 767, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 540, in render_template
    return view_obj.render_template(template, values)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1338, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "<decorator-gen-267>", line 2, in get_view_id
  File "/odoo/odoo-server/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 280, in get_view_id
    return super(View, self).get_view_id(xml_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1232, in get_view_id
    return view and view.id or self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_model.py", line 1436, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/odoo/odoo-server/odoo/addons/base/models/ir_model.py", line 1427, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/odoo/odoo-server/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_model.py", line 1416, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: product_label_report.report_producttemplatelabel
